apiVersion: 1
datasources:
  - name: Postgres-WAF
    uid: postgres-waf
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${GRAFANA_DB_USER}
    database: ${POSTGRES_DB}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1700
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    editable: true
